function startDashboardClient() {
  const {
    state,
    attachDashboardLazyMedia,
    pixelArtConversionRequests,
    toolWorkspaceImageExportRequests,
    pixelArtReadyWaiters,
    stageMeta,
    studioWorkflowSidebarMeta,
    toolsWorkspaceState,
    toolsWorkspaceStorageKeys,
    toolQuickActionStorageKeys,
    toolQuickActionState,
    studioRailExpandedStorageKey,
    studioRailHoverModeStorageKey,
    studioWorkflowSidebarModeStorageKey,
    workflowRightSidebarStateStorageKey,
    workflowRightSidebarWidthStorageKey,
    workflowRightSidebarTargets,
    request,
    getDashboardGuildChannelRuntimeHelpers,
    setDashboardText,
    switchDashboardView,
    setConsoleOverlayOpen,
    setDashboardSettingsRuntimeHelpers,
    getDashboardSettingsRuntimeHelpers,
    setDashboardGuildChannelRuntimeHelpers,
    loadChannelSettings,
    loadChannelPermissionSummary
  } = createDashboardClientBootstrapContext({
    getSwitchView: () => switchView,
    getConsoleHelpers: () => dashboardConsoleHelpers
  });
  const {
    escapeHtml,
    renderMarkdownHtml,
    renderMarkdownInto,
    setOutput,
    formatDateTime,
    clearChildren,
    setElementValue,
    setElementChecked,
    getModel3dFileUrl,
    getGeneratedImageFileUrl,
    getGeneratedAudioFileUrl,
    getGeneratedVideoFileUrl,
    buildAbsoluteDashboardUrl,
    downloadModel3dArtifact,
    collectPastedImages,
    collectDroppedImages
  } = createDashboardClientSharedBootstrapHelpers({
    setModel3dStatus: text => setModel3dStatus(text),
    getFilesToAiImages: () => filesToAiImages,
    getParseImageTextInputs: () => parseImageTextInputs
  });
  if (typeof configureDashboardToolsWorkspaceRuntime === "function") {
    configureDashboardToolsWorkspaceRuntime({
      state,
      toolsWorkspaceState,
      toolsWorkspaceStorageKeys,
      toolQuickActionState,
      toolQuickActionStorageKeys,
      pixelArtConversionRequests,
      toolWorkspaceImageExportRequests,
      pixelArtReadyWaiters,
      clearChildren,
      setOutput,
      request,
      buildAbsoluteDashboardUrl,
      getGeneratedImageFileUrl,
      getGeneratedVideoFileUrl,
      getModel3dFileUrl,
      getSelectedGeneratedImage: (...args) => getSelectedGeneratedImage(...args),
      getSelectedGeneratedModel: (...args) => getSelectedGeneratedModel(...args),
      getSelectedGeneratedVideo: (...args) => getSelectedGeneratedVideo(...args),
      getModel3dViewerTarget: (...args) => getModel3dViewerTarget(...args),
      resolveModel3dPreviewMedia: (...args) => resolveModel3dPreviewMedia(...args),
      loadImageHistory: (...args) => loadImageHistory(...args),
      refreshState: (...args) => getDashboardGuildChannelRuntimeHelpers().refreshState(...args),
      switchView: (...args) => switchDashboardView(...args)
    });
  }
  const {
    dashboardStudioSidebarHelpers,
    normalizeDashboardTheme,
    getDashboardThemeLabel,
    readDashboardThemePreference,
    shouldAnimateDashboardThemeTransition,
    setDashboardThemeTransitionEnabled,
    updateDashboardThemeButtons,
    setDashboardTheme,
    getNextDashboardTheme,
    normalizeMessenger,
    isDiscordOnlyView,
    getActiveView,
    restoreStudioRightSidebarAsides,
    syncStudioRightSidebar,
    getMessengerDisplayName,
    normalizeThemeTarget,
    applyMessengerThemeVariables,
    loadThemeConfig,
    applyThemeForCurrentContext,
    getSelectedMessengerRuntime,
    normalizeTelegramChatId,
    getSelectedTelegramChat,
    setSelectedTelegramChatId,
    setRuntimeOverlayOpen,
    setSettingsOverlayOpen,
    getRuntimeProgressValue,
    formatRuntimeMeta,
    updateMessengerRuntimeLaunchUi,
    renderMessengerRuntimePanel,
    updateMessengerWorkspaceSummary,
    applyMessengerSelectionUi,
    normalizeMatrixRoomId,
    normalizeScheduledTargetMessenger,
    refreshMeta,
    guildRefresh,
    getDashboardMessengerSubtitle,
    formatRelativeTime,
    getMessengerDashboardRecords,
    renderMessengerDashboardRecentMessages,
    renderMessengerDashboardActivityBars,
    renderMessengerDashboardCommandList,
    renderMessengerDashboardView
  } = createDashboardShellBootstrapHelpers({
    state,
    request,
    formatDateTime,
    clearChildren,
    escapeHtml,
    setDashboardText,
    getActiveView: () => getActiveView(),
    studioWorkflowSidebarMeta,
    workflowRightSidebarTargets,
    studioRailExpandedStorageKey,
    studioRailHoverModeStorageKey,
    studioWorkflowSidebarModeStorageKey,
    workflowRightSidebarStateStorageKey,
    workflowRightSidebarWidthStorageKey,
    updateAutomationTargetChips: () => updateAutomationTargetChips(),
    renderMessengerDashboardView: () => renderMessengerDashboardView(),
    getTelegramChatTitle
  });
  const dashboardMessengerWorkspaceHelpers = typeof createDashboardMessengerWorkspaceHelpers === "function"
    ? createDashboardMessengerWorkspaceHelpers({
        state,
        clearChildren,
        escapeHtml,
        formatDateTime,
        request,
        setSelectedTelegramChatId,
        updateMessengerWorkspaceSummary,
        renderMessengerDashboardView
      })
    : null;
  const {
    getMessengerBrowserUrl = () => "https://discord.com/channels/@me",
    renderTelegramChats = () => {},
    loadTelegramChats = async () => [],
    sendTelegramMessageFromUi = async () => {},
    sendWhatsAppMessageFromUi = async () => {}
  } = dashboardMessengerWorkspaceHelpers || {};
  const dashboardStudioRoutingBootstrapInput = createDashboardStudioRoutingBootstrapInput({
    state,
    request,
    setOutput,
    clearChildren,
    escapeHtml,
    formatDateTime,
    setElementValue,
    setElementChecked,
    getActiveView,
    normalizeMessenger,
    applyThemeForCurrentContext,
    applyMessengerSelectionUi,
    updateMessengerWorkspaceSummary,
    getMessengerDisplayName,
    resolveMessengerCompatibleView: (...args) => resolveMessengerCompatibleView(...args),
    switchDashboardView,
    normalizeTelegramChatId,
    setSelectedTelegramChatId,
    normalizeMatrixRoomId,
    renderMessengerRuntimePanel,
    stageMeta,
    unloadModel3dViewerPreview: (...args) => unloadModel3dViewerPreview(...args),
    unloadInactiveStudioWorkflowPreviews: (...args) => unloadInactiveStudioWorkflowPreviews(...args),
    applyStudioRailExpandedState: (...args) => applyStudioRailExpandedState(...args),
    updateStudioWorkflowSidebar: (...args) => updateStudioWorkflowSidebar(...args),
    dashboardStudioSidebarHelpers,
    dashboardShellLayoutHelpers: () => dashboardShellLayoutHelpers,
    renderImageList: (...args) => renderImageList(...args),
    filesToAiImages: () => filesToAiImages,
    readFileAsDataUrl: (...args) => readFileAsDataUrl(...args),
    collectDroppedImages,
    collectPastedImages,
    getGeneratedImageFileUrl,
    getGeneratedAudioFileUrl,
    getGeneratedVideoFileUrl,
    getModel3dFileUrl,
    buildAbsoluteDashboardUrl,
    getSelectedGeneratedModel: (...args) => getSelectedGeneratedModel(...args),
    getToolQuickActionSelection: (...args) => getToolQuickActionSelection(...args),
    updateVideoToolQuickActionState: (...args) => updateVideoToolQuickActionState(...args),
    convertImageUrlToPixelArt: (...args) => convertImageUrlToPixelArt(...args),
    convertImageUrlToNormalMap: (...args) => convertImageUrlToNormalMap(...args),
    openImageInPixelArtTool: (...args) => openImageInPixelArtTool(...args),
    openImageInNormalMapTool: (...args) => openImageInNormalMapTool(...args),
    handleModel3dLowPolyUploadSourceChange: (...args) => handleModel3dLowPolyUploadSourceChange(...args),
    setModel3dStatus: (...args) => setModel3dStatus(...args),
    loadModel3dHistory: (...args) => loadModel3dHistory(...args),
    getDashboardGuildChannelRuntimeHelpers,
    renderChannelBrowser: (...args) => renderChannelBrowser(...args),
    loadChannelSettings,
    loadChannelPermissionSummary,
    selectChannel: (...args) => selectChannel(...args),
    switchSubview: (...args) => switchSubview(...args),
    updateSelectionDetails: (...args) => updateSelectionDetails(...args),
    loadTelegramChats: (...args) => loadTelegramChats(...args),
    renderTelegramChats: (...args) => renderTelegramChats(...args),
    renderMessengerDashboardView,
    loadChannels: (...args) => loadChannels(...args),
    ensureAiWorkflowDataLoaded: (...args) => ensureAiWorkflowDataLoaded(...args),
    syncStudioRightSidebar,
    ensureImagePoolDataLoaded: (...args) => ensureImagePoolDataLoaded(...args),
    renderModel3dPoolSelectionList: (...args) => renderModel3dPoolSelectionList(...args),
    updateModel3dSourceHint: (...args) => updateModel3dSourceHint(...args),
    setDetailsPaneVisible: (...args) => setDetailsPaneVisible(...args),
    dashboardAiMediaStudioHelpers: () => dashboardAiMediaStudioHelpers,
    workflowRightSidebarTargets,
    studioRailExpandedStorageKey,
    studioWorkflowSidebarModeStorageKey,
    workflowRightSidebarStateStorageKey,
    workflowRightSidebarWidthStorageKey,
    studioWorkflowSidebarMeta,
    getDashboardAutomationViewHelpers: () => dashboardAutomationViewHelpers,
    updateScheduledSourceFields: () => updateScheduledSourceFields(),
    updateAutomationTargetChips: () => updateAutomationTargetChips(),
    resolveRequestedViewForMessenger: (...args) => resolveRequestedViewForMessenger(...args),
    renderModel3dUploadSourceList: (...args) => renderModel3dUploadSourceList(...args),
    renderModel3dViewer: (...args) => renderModel3dViewer(...args),
    resolveModel3dPreviewMedia: (...args) => resolveModel3dPreviewMedia(...args),
    renderModel3dPreviewGifDataUrl: (...args) => renderModel3dPreviewGifDataUrl(...args)
  });
  const dashboardStudioRoutingMediaBootstrapHelpers = typeof createDashboardStudioRoutingMediaBootstrapHelpers === "function"
    ? createDashboardStudioRoutingMediaBootstrapHelpers(dashboardStudioRoutingBootstrapInput)
    : null;
  const {
    dashboardMessagingHandlers,
    dashboardGuildSettingsUiHelpers,
    setHeroBotTag,
    setSelectedMessenger,
    loadSelectedGuildSettings,
    openChannelSettings,
    readStudioRailExpandedPreference,
    readStudioRailHoverModePreference,
    applyStudioRailExpandedState,
    setStudioRailHoverMode,
    setStudioRailExpanded,
    setWorkflowSidebarMode,
    readWorkflowRightSidebarPreference,
    applyWorkflowRightSidebarCollapsedState,
    setWorkflowRightSidebarCollapsed,
    readWorkflowRightSidebarWidthPreference,
    applyWorkflowRightSidebarWidthState,
    bindWorkflowRightSidebarResizers,
    bindStudioRailHoverExpansion,
    updateStudioWorkflowSidebar,
    getModel3dInitialExtraSampleText,
    getModel3dDestinationExtraSampleText,
    getScheduledModelPostOptionsModule,
    getAutomationScopeId,
    updateToolsPixelSliderReadouts,
    renderToolsPixelArt,
    maybeAutoConvertToolsPixel,
    loadToolsPixelSourceFile,
    downloadToolsPixelResult,
    resetToolsPixelTool,
    dashboardModel3dPostUiHelpers,
    updateModel3dPostOptionsUi,
    syncModel3dLowPolyPresetFromFaceCount,
    applyModel3dLowPolyPresetToFaceCount,
    readModel3dPostOptions,
    validateModel3dPostOptions,
    refreshModel3dPostDestinationOptions,
    dashboardAutomationChannelHelpers,
    refreshAutomationAndModelChannelSelectors,
    switchView,
    dashboardAiStudioLayoutHelpers,
    openAiSection,
    clearAiSectionFocus,
    applyAiSectionFocusState,
    applyShellPaneState,
    enhanceShellChrome,
    setDetailsPaneVisible,
    setWorkspacePaneVisible,
    syncResponsiveShell,
    bindShellOverlayEvents,
    dashboardAudioUiHelpers,
    setAudioGenerationStatus,
    setMusicGenerationStatus,
    loadAudioHistory,
    syncAudioPreviewForFocus,
    dashboardAiMediaStudioHelpers,
    mergeAiImages,
    clearAiImages,
    renderAiImageList,
    renderAskComposerAttachments,
    clearAskSkillModelUploads,
    clearAskFileUploads,
    mergeModerationImages,
    clearModerationImages,
    renderModerationImageList,
    setImageGenerationStatus,
    loadImageHistory,
    setVideoGenerationStatus,
    loadVideoHistory,
    dashboardGameEngineHelpers,
    dashboardModel3dQuickActionModalHelpers,
    unloadMediaStudioPreviewForFocus,
    refreshStudioPostTargetOptions,
    bindAiMediaStudioEvents
  } = dashboardStudioRoutingMediaBootstrapHelpers || {};
  const {
    dashboardDiscordWorkspaceHelpers,
    applySelectedUser,
    getUserSearchQuery,
    renderUserResults,
    loadUsers,
    renderGuildRail,
    selectGuild,
    updateSelectionDetails,
    loadChannels,
    renderChannelBrowser,
    selectChannel
  } = createDashboardDiscordWorkspaceBootstrapHelpers({
    state,
    request,
    setOutput,
    clearChildren,
    escapeHtml,
    loadBotMessages: (...args) => getDashboardGuildChannelRuntimeHelpers().loadBotMessages(...args),
    setWorkspacePaneVisible,
    dashboardGuildSettingsUiHelpers,
    loadSelectedGuildSettings,
    updateAutomationTargetChips: () => updateAutomationTargetChips(),
    getActiveView,
    refreshMeta,
    openChannelSettings,
    refreshState: (...args) => getDashboardGuildChannelRuntimeHelpers().refreshState(...args),
    loadAutomations: (...args) => loadAutomations(...args),
    refreshAutomationAndModelChannelSelectors
  });
  const {
    dashboardSettingsRuntimeHelpersProxy,
    dashboardWorkspacePanelHelpersProxy,
    dashboardUserSearchHandlersProxy,
    dashboardConsoleHelpersProxy,
    dashboardModel3dStudioEventBindingHelpersProxy
  } = createDashboardLateBoundBootstrapProxyHelpers({
    getDashboardSettingsRuntimeHelpers,
    getDashboardWorkspacePanelHelpers: () => dashboardWorkspacePanelHelpers,
    getDashboardUserSearchHandlers: () => dashboardUserSearchHandlers,
    getDashboardConsoleHelpers: () => dashboardConsoleHelpers,
    getDashboardModel3dStudioEventBindingHelpers: () => dashboardModel3dStudioEventBindingHelpers
  });
  const dashboardRootBootstrapTailHelpers = typeof createDashboardRootBootstrapTailHelpers === "function"
    ? createDashboardRootBootstrapTailHelpers({
        state,
        request,
        refreshMeta,
        guildRefresh,
        clearChildren,
        escapeHtml,
        formatDateTime,
        renderMarkdownInto,
        renderMessengerDashboardView,
        setOutput,
        setHeroBotTag,
        renderGuildRail,
        renderChannelBrowser,
        updateSelectionDetails,
        dashboardGuildSettingsUiHelpers,
        refreshAutomationAndModelChannelSelectors,
        setRefreshStatus: (...args) => setRefreshStatus(...args),
        loadMessengerRuntimes: (...args) => loadMessengerRuntimes(...args),
        loadChannels,
        getMessengerDisplayName,
        loadGlobalSettingsFromState: (...args) => loadGlobalSettingsFromState(...args),
        refreshAutomationTextSources: (...args) => refreshAutomationTextSources(...args),
        dashboardSettingsRuntimeHelpers: dashboardSettingsRuntimeHelpersProxy,
        getScheduledModelPostOptionsModule,
        getModel3dInitialExtraSampleText,
        getModel3dDestinationExtraSampleText,
        getAutomationScopeId,
        normalizeScheduledTargetMessenger,
        normalizeTelegramChatId,
        normalizeMatrixRoomId,
        formatImagePostProcessingRecipes: (...args) => formatImagePostProcessingRecipes(...args),
        parseImagePostProcessingRecipes: (...args) => parseImagePostProcessingRecipes(...args),
        setMultiSelectValues: (...args) => setMultiSelectValues(...args),
        getMultiSelectValues: (...args) => getMultiSelectValues(...args),
        setElementValue,
        setElementChecked,
        fillPresetSelect: (...args) => fillPresetSelect(...args),
        loadAutomationTextSources: (...args) => loadAutomationTextSources(...args),
        dashboardAutomationChannelHelpers,
        dashboardWorkspacePanelHelpers: dashboardWorkspacePanelHelpersProxy,
        saveMessagingGlobalSettingsFromUi: (...args) => saveMessagingGlobalSettingsFromUi(...args),
        saveComfyPathSettingsFromUi: (...args) => saveComfyPathSettingsFromUi(...args),
        saveLlmConnectionSettingsFromUi: (...args) => saveLlmConnectionSettingsFromUi(...args),
        saveImageLlmConnectionSettingsFromUi: (...args) => saveImageLlmConnectionSettingsFromUi(...args),
        saveModel3dLlmConnectionSettingsFromUi: (...args) => saveModel3dLlmConnectionSettingsFromUi(...args),
        switchView,
        openChannelSettings,
        dashboardUserSearchHandlers: dashboardUserSearchHandlersProxy,
        bindAutomationStudioEvents: (...args) => bindAutomationStudioEvents(...args),
        dashboardAiStudioLayoutHelpers,
        dashboardConsoleHelpers: dashboardConsoleHelpersProxy,
        dashboardGameEngineHelpers,
        dashboardMessagingHandlers,
        dashboardModel3dStudioEventBindingHelpers: dashboardModel3dStudioEventBindingHelpersProxy,
        handlePixelArtToolMessage,
        handleToolWorkspaceBridgeMessage,
        bindAiActions: (...args) => bindAiActions(...args),
        bindAiMediaStudioEvents,
        bindImagePoolEvents: (...args) => bindImagePoolEvents(...args),
        bindAutomationTextSourceEvents: (...args) => bindAutomationTextSourceEvents(...args),
        bindToolsViewEvents,
        bindAiToolQuickActionEvents,
        bindShellOverlayEvents,
        enhanceShellChrome,
        applyAiSectionFocusState,
        updateStudioWorkflowSidebar,
        setStudioRailExpanded,
        readStudioRailHoverModePreference,
        setStudioRailHoverMode,
        setWorkflowSidebarMode,
        readStudioRailExpandedPreference,
        readWorkflowRightSidebarPreference,
        readWorkflowRightSidebarWidthPreference,
        applyWorkflowRightSidebarCollapsedState,
        applyWorkflowRightSidebarWidthState,
        bindWorkflowRightSidebarResizers,
        bindStudioRailHoverExpansion,
        syncResponsiveShell,
        applyStudioRailExpandedState,
        setDashboardTheme,
        readDashboardThemePreference,
        setSelectedMessenger,
        renderAiImageList,
        renderModerationImageList,
        updateModel3dPostOptionsUi,
        applyModel3dLowPolyPresetToFaceCount,
        syncModel3dLowPolyPresetFromFaceCount,
        setModel3dStatus: (...args) => setModel3dStatus(...args),
        setImageGenerationStatus,
        setAudioGenerationStatus,
        setMusicGenerationStatus,
        setVideoGenerationStatus,
        updateModel3dThreeVariantUi: (...args) => updateModel3dThreeVariantUi(...args),
        updateModel3dViewerMaterialToggleButtons: (...args) => updateModel3dViewerMaterialToggleButtons(...args),
        setModel3dPreviewStatus: (...args) => setModel3dPreviewStatus(...args),
        setModel3dThreeStatus: (...args) => setModel3dThreeStatus(...args),
        renderMessengerRuntimePanel,
        renderTelegramChats,
        updateMessengerWorkspaceSummary,
        updateMessengerRuntimeLaunchUi,
        setRuntimeOverlayOpen,
        setSettingsOverlayOpen,
        wireModelImagePicker,
        getModel3dSelectedPool: (...args) => getModel3dSelectedPool(...args),
        renderModel3dPoolSelectionList: (...args) => renderModel3dPoolSelectionList(...args),
        updateModel3dSourceHint: (...args) => updateModel3dSourceHint(...args),
        updateModel3dEditRoughnessValue: (...args) => updateModel3dEditRoughnessValue(...args),
        loadAutomationPresets: (...args) => loadAutomationPresets(...args),
        applyGlobalSettingsToUi: (...args) => applyGlobalSettingsToUi(...args),
        describeClientError: (...args) => describeClientError(...args),
        normalizeMessenger,
        controlSelectedMessengerRuntime: (...args) => controlSelectedMessengerRuntime(...args),
        loadTelegramChats: (...args) => loadTelegramChats(...args),
        setSelectedTelegramChatId: (...args) => setSelectedTelegramChatId(...args),
        getMessengerBrowserUrl,
        clearAiSectionFocus,
        refreshActiveArtToolImagePoolBridge: (...args) => refreshActiveArtToolImagePoolBridge(...args),
        ensureImagePoolDataLoaded: (...args) => ensureImagePoolDataLoaded(...args),
        getDashboardThemeLabel,
        getNextDashboardTheme,
        workflowRightSidebarTargets,
        setWorkflowRightSidebarCollapsed,
        applyQuickComfyPathSettingsToUi: (...args) => applyQuickComfyPathSettingsToUi(...args),
        applyQuickFfmpegSettingsToUi: (...args) => applyQuickFfmpegSettingsToUi(...args),
        readQuickComfyPathSettingsFromUi: (...args) => readQuickComfyPathSettingsFromUi(...args),
        setComfyPathSettingsStatus: (...args) => setComfyPathSettingsStatus(...args),
        setQuickComfyPathSettingsStatus: (...args) => setQuickComfyPathSettingsStatus(...args),
        saveQuickFfmpegSettingsFromUi: (...args) => saveQuickFfmpegSettingsFromUi(...args),
        saveMessengerRuntimeSettingsFromUi: (...args) => saveMessengerRuntimeSettingsFromUi(...args),
        runInstallerFromUi: (...args) => runInstallerFromUi(...args),
        clearAiImages,
        renderAskComposerAttachments,
        clearAskSkillModelUploads,
        clearAskFileUploads,
        sendTelegramMessageFromUi,
        sendWhatsAppMessageFromUi,
        openAiSection,
        setConsoleOverlayOpen
      })
    : null;
  const {
    dashboardAutomationViewHelpers = null,
    updateScheduledTargetModeUi = function updateScheduledTargetModeUiFallback() {},
    updateScheduledSourceFields = function updateScheduledSourceFieldsFallback() {},
    updateScheduledModelPostOptionsUi = function updateScheduledModelPostOptionsUiFallback() {},
    updateJoinSourceFields = function updateJoinSourceFieldsFallback() {},
    updateAutomationTargetChips = function updateAutomationTargetChipsFallback() {},
    dashboardAutomationStudioHelpers = null,
    dashboardAutomationBootstrapHelpers: lateAutomationBootstrapHelpers = null,
    loadOllamaModels,
    syncWorkflowLlmModelSelectionUi,
    syncLlmModelSelectionUi,
    getSelectedLlmModelsFromUi,
    saveSelectedLlmModelsFromUi,
    loadActiveLlmModels,
    switchSubview,
    switchDetailTab,
    bindSubviewTabs,
    initializeFoldAccordions,
    updateBotMessageSelectionSummary = function updateBotMessageSelectionSummaryFallback() {},
    renderBotMessageList = function renderBotMessageListFallback() {},
    guildRuntimeHelpers = null,
    loadGuilds,
    scheduleGuildRefreshRetry,
    loadDashboardDiscordChannels,
    loadDashboardDiscordMessages,
    renderGuildChannelPlan,
    renderModerationSimulation,
    loadBotMessages,
    refreshState,
    initializeWorkspace,
    renderScheduledAutomationList,
    renderJoinAutomationList,
    setScheduledForm,
    setJoinForm,
    loadAutomations,
    dashboardSettingsEventBindingHelpers = null,
    dashboardBootstrapStart = async function dashboardBootstrapStartFallback() {}
  } = dashboardRootBootstrapTailHelpers || {};
  const dashboardPostRootBootstrapAssemblyHelpers = createDashboardPostRootBootstrapAssemblyHelpers({
    state,
    splitLines,
    clearChildren,
    escapeHtml,
    formatDateTime,
    attachDashboardLazyMedia,
    buildAbsoluteDashboardUrl,
    getGeneratedImageFileUrl,
    getModel3dFileUrl,
    request,
    setOutput,
    createImageId,
    readBlobAsDataUrl,
    downloadModel3dArtifact,
    updateModel3dToolQuickActionState,
    getDashboardGuildChannelRuntimeHelpers,
    dashboardAiStudioLayoutHelpers,
    dashboardModel3dQuickActionModalHelpers,
    lateAutomationBootstrapHelpers,
    renderMessengerDashboardView,
    syncLlmModelSelectionUi,
    syncWorkflowLlmModelSelectionUi,
    setElementValue,
    setElementChecked,
    normalizeMessenger,
    getActiveView,
    isDiscordOnlyView,
    loadUsers,
    loadImageHistory,
    loadAudioHistory,
    loadVideoHistory,
    convertImageUrlToPixelArt,
    convertImageUrlToNormalMap,
    sendImageUrlToToolBySourceToken,
    clearModerationImages,
    clearAiImages,
    clearAskSkillModelUploads,
    clearAskFileUploads,
    uploadModelImageFile,
    unloadMediaStudioPreviewForFocus,
    syncAudioPreviewForFocus,
    refreshActiveArtToolImagePoolBridge,
    dashboardAiMediaStudioHelpers,
    switchView,
    dashboardAutomationViewHelpers,
    readModel3dPostOptions,
    validateModel3dPostOptions,
    setWorkflowSidebarMode,
    setWorkflowRightSidebarCollapsed,
    renderMarkdownInto,
    loadChannels,
    renderMessengerRuntimePanel,
    updateMessengerWorkspaceSummary,
    setDetailsPaneVisible
  });
  setDashboardSettingsRuntimeHelpers(dashboardPostRootBootstrapAssemblyHelpers.dashboardSettingsRuntimeHelpers);
  const {
    applyGlobalSettingsToUi,
    loadGlobalSettingsFromState,
    saveLlmConnectionSettingsFromUi,
    saveImageLlmConnectionSettingsFromUi,
    saveModel3dLlmConnectionSettingsFromUi,
    saveComfyPathSettingsFromUi,
    saveMessagingGlobalSettingsFromUi,
    saveQuickFfmpegSettingsFromUi,
    saveMessengerRuntimeSettingsFromUi,
    loadMessengerRuntimes,
    controlSelectedMessengerRuntime,
    runInstallerFromUi,
    describeClientError,
    setRefreshStatus,
    setComfyPathSettingsStatus,
    setQuickComfyPathSettingsStatus,
    setQuickFfmpegSettingsStatus,
    applyQuickComfyPathSettingsToUi,
    applyQuickFfmpegSettingsToUi,
    readQuickComfyPathSettingsFromUi,
    resolveMessengerCompatibleView,
    resolveRequestedViewForMessenger,
    formatImagePostProcessingRecipes,
    parseImagePostProcessingRecipes,
    dashboardConsoleHelpers,
    getBotShortLabel,
    dashboardShellLayoutHelpers,
    dashboardWorkspacePanelHelpers,
    dashboardUserSearchHandlers,
    dashboardAiActionHelpers,
    bindAiActions,
    dashboardImagePoolHelpers,
    getImagePoolById,
    loadImagePoolsBase,
    loadImagePools,
    dashboardModel3dBootstrapAssemblyHelpers,
    dashboardModel3dRuntimeStateHelpers,
    updateModel3dEditSelectedModelName,
    updateModel3dEditRoughnessValue,
    getSelectedGeneratedModel,
    getSelectedGeneratedImage,
    getSelectedGeneratedVideo,
    dashboardModel3dSourceHelpers,
    inferModelImageFileNameHint,
    normalizeModel3dLocalImageSourcePath,
    extractUploadedModelImageFileNameFromSource,
    extractGeneratedImagePathFromSource,
    resolveModel3dSourcePreviewUrl,
    getModel3dUploadSources,
    getModel3dSelectedPool,
    syncModel3dSelectedPoolSources,
    renderModel3dSourceList,
    renderModel3dUploadSourceList,
    renderModel3dPoolSelectionList,
    updateModel3dSourceHint,
    setModel3dGenerationBusy,
    collectModel3dSourceCandidates,
    readModel3dLowPolyOptionsFromUi,
    summarizeMetallicDecision,
    summarizeRealWorldHeightDecision,
    postGeneratedModelToExternalMessengerFromStudio,
    dashboardModel3dInspectorHelpers,
    dashboardModel3dViewerHelpers,
    model3dViewer,
    unloadModel3dViewerPreview,
    activateModel3dViewerPreview,
    handleModel3dLowPolyUploadSourceChange,
    loadModel3dHistory,
    scheduleModel3dHistoryRefresh,
    renderModel3dHistory,
    renderModel3dPreviewMedia,
    getModel3dViewerTarget,
    resolveModel3dPreviewMedia,
    renderModel3dViewer,
    renderModel3dPreviewGifDataUrl,
    exportModel3dPreviewGif,
    setModel3dThreeVariant,
    updateModel3dThreeVariantUi,
    setModel3dViewerWireframeEnabled,
    setModel3dViewerMetallicEnabled,
    updateModel3dViewerMaterialToggleButtons,
    updateModel3dViewerRoughnessUi,
    setModel3dViewerRoughness,
    setModel3dViewerTextureEnabled,
    setModel3dViewerMaterialMode,
    setModel3dViewerFlatShadingEnabled,
    setModel3dViewerGridEnabled,
    setModel3dViewerSkyboxEnabled,
    setModel3dViewerRigVisible,
    setModel3dViewerAxisMode,
    getModel3dPreviewRenderOptions,
    applyModel3dPreviewViewSettings,
    describeModel3dScaleDecision,
    setModel3dStatus,
    getModel3dStatusText,
    setModel3dPreviewStatus,
    setModel3dThreeStatus,
    dashboardModel3dViewportModalHelpers,
    updateModel3dGifExportBackgroundField,
    openModel3dGifExportModal,
    closeModel3dGifExportModal,
    readModel3dGifExportOptions,
    openSelectedModelInBlender,
    dashboardModel3dStudioActionHelpers,
    requestModel3dGenerationWithPreviewStream,
    runModel3dGenerationFromStudio,
    runModel3dSeparateByLoosePartsForSelectedModel,
    runLowPolyGenerationForSelectedModel,
    runModel3dLlmScaleForSelectedModel,
    renderAutoRigVerification,
    openAutoRigPanelForSelectedModel,
    runAutoRigPreviewForSelectedModel,
    finalizeAutoRigForSelectedModel,
    dashboardModel3dViewportControlHelpers,
    dashboardModel3dStudioEventBindingHelpers,
    dashboardAiWorkflowDataHelpers,
    unloadAudioElementPreview,
    unloadInactiveStudioWorkflowPreviews,
    ensureImagePoolDataLoaded,
    ensureAiWorkflowDataLoaded,
    bindImagePoolEvents,
    bindAutomationStudioEvents,
    loadAutomationPresets,
    refreshAutomationTextSources,
    dashboardAutomationTextSourceHelpers,
    fillPresetSelect,
    setMultiSelectValues,
    addMultiSelectValues,
    getMultiSelectValues,
    prefillAutomationTextSource,
    loadAutomationTextSources,
    updateAutomationTextPromptPreset,
    bindAutomationTextSourceEvents
  } = dashboardPostRootBootstrapAssemblyHelpers;
  dashboardAutomationBootstrapHelpers = lateAutomationBootstrapHelpers;
  setDashboardGuildChannelRuntimeHelpers(guildRuntimeHelpers);
  dashboardBootstrapStart()
    .then(() => window.dispatchEvent(new Event("dashboard:ready")))
    .catch(error => setOutput(error.message || "Failed to load dashboard."));
}
