function createDashboardStudioRoutingBootstrapInput(input) {
  const resolveValue = value => typeof value === "function" ? value() : value;
  const studioSidebarHelpers = createLazyDashboardHelperProxy(
    () => resolveValue(input.dashboardStudioSidebarHelpers),
    {}
  );
  const shellLayoutHelpers = createLazyDashboardHelperProxy(
    () => resolveValue(input.dashboardShellLayoutHelpers),
    {}
  );
  const dashboardAiMediaStudioHelpers = createLazyDashboardHelperProxy(
    () => resolveValue(input.dashboardAiMediaStudioHelpers),
    {}
  );
  return {
    state: input.state,
    request: input.request,
    setOutput: input.setOutput,
    clearChildren: input.clearChildren,
    escapeHtml: input.escapeHtml,
    formatDateTime: input.formatDateTime,
    setElementValue: input.setElementValue,
    setElementChecked: input.setElementChecked,
    getActiveView: input.getActiveView,
    normalizeMessenger: input.normalizeMessenger,
    applyThemeForCurrentContext: input.applyThemeForCurrentContext,
    applyMessengerSelectionUi: input.applyMessengerSelectionUi,
    updateMessengerWorkspaceSummary: input.updateMessengerWorkspaceSummary,
    getMessengerDisplayName: input.getMessengerDisplayName,
    resolveMessengerCompatibleView: (...args) => input.resolveMessengerCompatibleView(...args),
    switchDashboardView: input.switchDashboardView,
    normalizeTelegramChatId: input.normalizeTelegramChatId,
    setSelectedTelegramChatId: input.setSelectedTelegramChatId,
    normalizeMatrixRoomId: input.normalizeMatrixRoomId,
    renderMessengerRuntimePanel: input.renderMessengerRuntimePanel,
    stageMeta: input.stageMeta,
    unloadModel3dViewerPreview: input.unloadModel3dViewerPreview,
    unloadInactiveStudioWorkflowPreviews: input.unloadInactiveStudioWorkflowPreviews,
    applyStudioRailExpandedState: input.applyStudioRailExpandedState,
    updateStudioWorkflowSidebar: input.updateStudioWorkflowSidebar,
    studioSidebarHelpers,
    shellLayoutHelpers,
    renderImageList: (...args) => input.renderImageList(...args),
    get filesToAiImages() {
      return resolveValue(input.filesToAiImages);
    },
    readFileAsDataUrl: input.readFileAsDataUrl,
    collectDroppedImages: input.collectDroppedImages,
    collectPastedImages: input.collectPastedImages,
    getGeneratedImageFileUrl: input.getGeneratedImageFileUrl,
    getGeneratedAudioFileUrl: input.getGeneratedAudioFileUrl,
    getGeneratedVideoFileUrl: input.getGeneratedVideoFileUrl,
    getModel3dFileUrl: input.getModel3dFileUrl,
    buildAbsoluteDashboardUrl: input.buildAbsoluteDashboardUrl,
    getSelectedGeneratedModel: (...args) => input.getSelectedGeneratedModel(...args),
    getToolQuickActionSelection: input.getToolQuickActionSelection,
    updateVideoToolQuickActionState: input.updateVideoToolQuickActionState,
    convertImageUrlToPixelArt: input.convertImageUrlToPixelArt,
    convertImageUrlToNormalMap: input.convertImageUrlToNormalMap,
    openImageInPixelArtTool: input.openImageInPixelArtTool,
    openImageInNormalMapTool: input.openImageInNormalMapTool,
    handleModel3dLowPolyUploadSourceChange: input.handleModel3dLowPolyUploadSourceChange,
    setModel3dStatus: input.setModel3dStatus,
    loadModel3dHistory: input.loadModel3dHistory,
    refreshState: (...args) => input.getDashboardGuildChannelRuntimeHelpers().refreshState(...args),
    loadBotMessages: (...args) => input.getDashboardGuildChannelRuntimeHelpers().loadBotMessages(...args),
    renderChannelBrowser: input.renderChannelBrowser,
    loadChannelSettings: input.loadChannelSettings,
    loadChannelPermissionSummary: input.loadChannelPermissionSummary,
    selectChannel: input.selectChannel,
    switchSubview: (...args) => input.switchSubview(...args),
    updateSelectionDetails: (...args) => input.updateSelectionDetails(...args),
    loadTelegramChats: (...args) => input.loadTelegramChats(...args),
    renderTelegramChats: (...args) => input.renderTelegramChats(...args),
    renderMessengerDashboardView: input.renderMessengerDashboardView,
    loadChannels: (...args) => input.loadChannels(...args),
    ensureAiWorkflowDataLoaded: (...args) => input.ensureAiWorkflowDataLoaded(...args),
    syncStudioRightSidebar: input.syncStudioRightSidebar,
    ensureImagePoolDataLoaded: (...args) => input.ensureImagePoolDataLoaded(...args),
    renderModel3dPoolSelectionList: (...args) => input.renderModel3dPoolSelectionList(...args),
    updateModel3dSourceHint: (...args) => input.updateModel3dSourceHint(...args),
    setDetailsPaneVisible: (...args) => input.setDetailsPaneVisible(...args),
    refreshImageEditSourceOptions: () => dashboardAiMediaStudioHelpers.refreshImageEditSourceOptions?.(),
    syncImageStudioPreviewTarget: () => dashboardAiMediaStudioHelpers.syncImageStudioPreviewTarget?.(),
    workflowRightSidebarTargets: input.workflowRightSidebarTargets,
    studioRailExpandedStorageKey: input.studioRailExpandedStorageKey,
    workflowRightSidebarStateStorageKey: input.workflowRightSidebarStateStorageKey,
    workflowRightSidebarWidthStorageKey: input.workflowRightSidebarWidthStorageKey,
    studioWorkflowSidebarMeta: input.studioWorkflowSidebarMeta,
    dashboardAutomationViewHelpers: () => input.getDashboardAutomationViewHelpers(),
    updateScheduledSourceFields: () => input.updateScheduledSourceFields(),
    updateAutomationTargetChips: () => input.updateAutomationTargetChips(),
    resolveRequestedViewForMessenger: (...args) => input.resolveRequestedViewForMessenger(...args),
    renderModel3dUploadSourceList: (...args) => input.renderModel3dUploadSourceList(...args),
    renderModel3dViewer: (...args) => input.renderModel3dViewer(...args),
    resolveModel3dPreviewMedia: (...args) => input.resolveModel3dPreviewMedia(...args),
    renderModel3dPreviewGifDataUrl: (...args) => input.renderModel3dPreviewGifDataUrl(...args)
  };
}
